### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by profgandhi** [profgandhi/Quirky-Captons#1]
- [x] Add to the caption database with more topics
- [x] Single photo selfie captions
- [x] Edge cases nature-wedding case
- [x] Report
- [ ] Improve frontend [Dynamic table]
